image: node:latest

stages:
  - deploy

before_script:
  - cp $NPM_RC ~/.npmrc

deploy:
  stage: deploy
  script:
    - echo "//gitlab.example.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
